# Generated by Django 5.0.3 on 2024-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO cars_car (brand, model, body, color, instructions)"
            "VALUES ('CITROEN', 'XCARA', 'HATCHBACK', 'BLUE', 'Удар в правую сторону (перед)');"
        ),
    ]
