# Generated by Django 5.0.3 on 2024-03-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='model_auto',
        ),
    ]
